<!DOCTYPE html>
<html>
    <head>
        <?php $this->setMeta('Content-Type', 'text/html; charset=utf-8'); ?>
        <?php $this->setMeta('Refresh', $this->refresh); ?>
        
        <style>
            *
            {
                cursor: none !important;
            }
            body
            {
                background-color: #FFFFFF;
                margin: 0;
                padding: 0;
                overflow-x: hidden;
                overflow-y: hidden;
                cursor: none;
            }
            #content
            {
                cursor: none;
            }
        </style> 
        
        <?php $this->setTitle('iPlayer'); ?>
    </head>
    <body>
        <div id="content">
            <object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=8,0,0,0" width="800" height="600">
               <param name="allowScriptAccess" value="sameDomain" />
               <param name="movie" value="<?php $this->setPrint($this->media, false); ?>" />
               <param name="menu" value="false" />
               <param name="quality" value="high" />
               <param name="pluginspage" value="http://www.macromedia.com/go/getflashplayer" />
               <embed src="<?php $this->setPrint($this->media, false); ?>" menu="false" quality="high" width="800" height="600" allowScriptAccess="sameDomain" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer">
              </object>           
        </div>
    </body>
</html>